;;; gptel-fabric-pkg.el --- Package metadata for gptel-fabric -*- lexical-binding: t; -*-

;; This file is automatically generated by the package build process.

(define-package "gptel-fabric" "0.1.0"
  "Use Fabric prompts with gptel"
  '((emacs "27.1")
    (gptel "0.8.0"))
  :keywords '("convenience" "tools" "comm" "llm" "ai")
  :authors '(("Alex Olkhovskiy" . "gtptel-fabric@monoinbox.co.uk"))
  :maintainer '("Alex Olkhovskiy" . "gtptel-fabric@monoinbox.co.uk")
  :url "https://github.com/lxol/gptel-fabric")

;;; gptel-fabric-pkg.el ends here
